### PR TITLE
#209/Create-a-database-method-to-create-a-block

### LINKED ISSUE #209: Create a database method to create a block

### PR DESCRIPTION
**Pull request by gbudau**
close #209

### CODE REVIEW

**Comment by Damrod** [comment]
Very didactic splitting of the issue in MRs. It will be much easier to retrace your steps, when we will need to. Thank you!

**Review by Damrod — APPROVED** [review]
LGTM!

**Review by fizcamposancos — APPROVED** [review]
Good job! Just a question, is related with the structure of the backend, more or less the same as what we are disccusing about chats, a module for each relation between users, block.module, friend.module,...? Or a relationship module?

**Comment by gbudau** [comment]
> Good job! Just a question, is related with the structure of the backend, more or less the same as what we are disccusing about chats, a module for each relation between users, block.module, friend.module,...? Or a relationship module?

@fizcamposancos Sure :+1:. I've added this change in #214

**Pull request merged**
