### PR TITLE
#564/Sometimes the game configuration option is skipped

### LINKED ISSUE #564: Sometimes the game configuration option is skipped
In some games, both players get redirected to the "Ready" page, skipping the game configuration, and the game mode is `unknown`.

### PR DESCRIPTION
**Pull request by gbudau**
close #564

### CODE REVIEW

**Review by vdedios — APPROVED** [review]
Nice, thank you for this fix 👏

**Comment by gbudau** [comment]
Oops, I did a rebase onto and push force with a wrong commit (latest instead of previous), and Github closed the PR since there are no changes :sweat_smile:

```sh
git rebase --onto main 56063c95321a676f46a9ba01ca3a61ddc8896523
git push -f
```

I will try to redo the changes and reopen the PR.

**Comment by gbudau** [comment]
Done, same changes https://github.com/42AGV/ft_transcendence/compare/56063c95321a676f46a9ba01ca3a61ddc8896523..66607ae3d7e12c6606855fcd9bb9a2fe3d8db646

**Comment by gbudau** [comment]
Thank you! :tada:

**Pull request merged**
