### PR TITLE
#276/reorder make clean rule

### PR DESCRIPTION
**Pull request by Damrod**
When running make clean, first we remove the generated code, and then stop the running deployment of our app. If a browser is actively running the app, it will complain that the generated files are missing, before it goes down. Removing the files AFTER stopping the deployment would make a more graceful shutdown.

### CODE REVIEW

**Review by vdedios — APPROVED** [review]
Not directly related to this PR but it would be nice to have a `test` rule so we can pass the full test suite. What do you think?

**Review by gbudau — APPROVED** [review]
Thanks!

**Review by fizcamposancos — APPROVED** [review]
LGTM

**Comment by Damrod** [comment]
> Not directly related to this PR but it would be nice to have a `test` rule so we can pass the full test suite. What do you think?

why not

**Pull request merged**
