### PR TITLE
Connect Api42Service

### PR DESCRIPTION
**Pull request by gbudau**

### CODE REVIEW

**Comment by gbudau** [comment]
@vdedios, I did this PR as an example, but it's also functional. Do you prefer that we close or merge it?

**Review by vdedios — APPROVED** [review]
👍👍👍

**Review by Damrod — APPROVED** [review]
Much cleaner now, and not repeated code. 100% for merging it

**Review by fizcamposancos — APPROVED** [review]
Very good, sorry for the delay

**Pull request merged**
