### PR TITLE
frontend boilerplate added

### PR DESCRIPTION
**Pull request by Damrod**
Framework boilerplate as created by create react app from webstorm

### CODE REVIEW

**Review by gbudau — APPROVED** [review]
LGTM :rocket:

**Review by vdedios — CHANGES_REQUESTED** [review]
Thanks for creating it! But, after thinking on it, I believe a more appropriate name for the frontend folder could be "webapp"

**Comment by Damrod** [comment]
> Thanks for creating it! But, after thinking on it, I believe a more appropriate name for the frontend folder could be "webapp"

better now?

**Review by vdedios — APPROVED** [review]
LGTM ✈️

**Comment by vdedios** [comment]
We could merge this one?

**Review by fizcamposancos — APPROVED** [review]
Everything looks good!

**Pull request merged**
