### PR TITLE
#353/created discover chatroom page

### PR DESCRIPTION
**Pull request by Damrod**
As described in #353

### CODE REVIEW

**Comment by Damrod** [comment]
Maybe we could like to filter from the discover page the chatrooms where the user is already a member to have two disjoint sets of chatrooms?

**Comment by fizcamposancos** [comment]
> Maybe we would like to filter from the discover page the chatrooms where the user is already a member to have two disjoint sets of chatrooms?

I  would leave it like this, discover page showing everything, just in case you thought you were not a member and start searching in the discover section.
Another issue would be how we deal with one-to-one chats. The ones you are already chatting with in the chat page. And in the discover page? Only chatrooms or also all the users (as possible one-to-one chats)?

**Comment by fizcamposancos** [comment]
Question: in the chat page we are ordering by chatname, each set of chatroom loaded, and in the discover page? It looks strange

**Review by fizcamposancos — APPROVED** [review]
Beside the comments, nice job!!

**Review by vdedios — APPROVED** [review]
Good 👌 👌

**Review by gbudau — APPROVED** [review]
Thank you for this feature! LGTM :rocket:

**Comment by gbudau** [comment]
BTW, awesome detail with the Discover/Chat button arrow direction :heart:

**Pull request merged**
