### PR TITLE
Add backend boilerplate

### LINKED ISSUE #8: NestJS boilerplate

### PR DESCRIPTION
**Pull request by gbudau**
Framework boilerplate as created by Nest CLI

close #8

### CODE REVIEW

**Comment by vdedios** [comment]
I'll name this differently, backend is a little broad concept. Ideas? For example, I like more something like `transcendence-app `

**Comment by gbudau** [comment]
> I'll name this differently, backend is a little broad concept. Ideas? For example, I like more something like `transcendence-app `

More ideas:

`web-app` / `api-app`
`web-client` / `api-server`

I don't have any preference in this case.

**Comment by Damrod** [comment]
looks good to me.

**Review by Damrod — APPROVED** [review]
LGTM

**Review by vdedios — APPROVED** [review]

**Comment by vdedios** [comment]
I think we could merge this one?

**Comment by gbudau** [comment]
I think we can merge it. @fizcamposancos, what do you think?

**Comment by fizcamposancos** [comment]
> I think we can merge it. @fizcamposancos, what do you think?

Yes, sorry, we can merge it

**Review by fizcamposancos — APPROVED** [review]
Everything looks good to me

**Comment by gbudau** [comment]
:heart: Thank you!

**Pull request merged**
