### PR TITLE
#452/score component

### LINKED ISSUE #452: ⚛️ score component
In order to report the players' score in a game, we need a scoring component, that will have, on the left, player's A avatar and name, in the center the score, and on the right player's B avatar and name, as displayed in figma [here](https://www.figma.com/file/mlRqpQ9bJ14VDYFW7u2XMG?node-id=2003:7843#352788441)

### PR DESCRIPTION
**Pull request by fizcamposancos**
close #452

### CODE REVIEW

**Comment by Damrod** [comment]
This is not in draft, but you haven't requested review either. Did you intend to request a review and you forgot? Or it should still be in draft?

**Comment by fizcamposancos** [comment]
> This is not in draft, but you haven't requested review either. Did you intend to request a review and you forgot? Or it should still be in draft?

Yes, sorry. I forgot

**Comment by Damrod** [comment]
I think in desktop view the component sub elements should be somehow arranged vertically. Since we decided to arrange the game arena vertically, and desktop are horizontal screens, we don't have room to spare vertically, but we have plenty of room horizontally.

something like this should work:
Screenshot from 2023-02-14 10-50-09

**Review by Damrod — APPROVED** [review]
Besides the comment, LGTM! Thank you!

**Review by gbudau — APPROVED** [review]
Thank you for this feature! LGTM and nice implementation :rocket:

**Pull request merged**
